### ISSUE TITLE
Malta No Longer Beaconing or Witnessing

### ISSUE THREAD

**Issue by claydon99** [helium/lorawan-h3#10]
For some reason since the 14th of December, all hotspots in Malta (EU) have simply stopped sending out beacons and witnessing eachother.

Was hoping that it would be fix with the latest update but still none of the hotspots are working.

**Comment by vihu** [comment]
This is a known issue and will be fixed in the upcoming weeks. It requires preparing and issuing updated chain variables for region parameters on the blockchain, which takes time and will be communicated further on discord/helium blog.

Refer:
https://github.com/helium/lorawan-h3/pull/9
https://github.com/helium/blockchain-core/pull/1176

Specifically:
https://github.com/helium/blockchain-core/pull/1176/files#diff-93d9355a4e6458d771511e8617c49d08859bf0747564397bda10f6e60bbf88f5R343

**Comment by JamesSamsonyan** [comment]
Thank you Rahul for the update. As you understand many people including me have many miners yet to set up. It's a lot of investment and I just wanted to know your opinion if this January it will be fixed? Including Armenia. Thank you
